<a href="https://colab.research.google.com/github/NishantKumar-2005/PortFolio/blob/main/TensorIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
if torch.cuda.is_available():
  print("cuda is available")
  print(torch.cuda.get_device_name(0))
else:
  print("cuda is not available")

cuda is available
Tesla T4


Creating a Tensor in Pytorch

In [4]:
#Using Empty
torch.empty(2,3)


tensor([[2.2421e-43, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using one
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.1815, 0.5660, 0.1041],
        [0.5572, 0.5526, 0.3557]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

Tensor Shapes

In [11]:
x=torch.tensor([[1,2,3],[2,3,4]])
x.shape

torch.Size([2, 3])

In [12]:
torch.empty_like(x)

tensor([[       433791696896, 7310593858020254331, 3616445622929465956],
        [6067810143136918837, 3544959874074555952, 6500161235004568110]])

In [13]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.9326, 0.6252, 0.7399],
        [0.5751, 0.8162, 0.0304]])

DataType of Tensor


In [15]:
x.dtype

torch.int64

In [16]:
torch.tensor([[1,2,4],[2,34,5]],dtype=torch.float32)


tensor([[ 1.,  2.,  4.],
        [ 2., 34.,  5.]])

In [17]:
#to change the Dtype of Tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 3., 4.]])